import {
  type ParsedUserMessage,
  parseUserMessage,
} from "../server/core/claude-code/functions/parseUserMessage";

type TitleContentItem = string | { type: string; text?: string };

type ConversationForTitle = {
  type: string;
  isSidechain?: boolean;
  message?: {
    content?: string | ReadonlyArray<TitleContentItem>;
  };
};

type ConversationForCount = {
  type: string;
  isSidechain?: boolean;
  message?: {
    content?: string | ReadonlyArray<{ type: string } | string>;
  };
};

export type SessionDisplayMeta = {
  title: string;
  visibleMessageCount: number;
};

const ignoredCommands = new Set([
  "/clear",
  "/login",
  "/logout",
  "/exit",
  "/mcp",
  "/memory",
]);

const ignoredExactTexts = new Set([
  "Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.",
  "Warmup",
]);

const SESSION_TITLE_MAX_LENGTH = 40;

const normalizeTitleText = (text: string) => {
  const firstNonEmptyLine =
    text
      .split(/\r?\n/)
      .map((line) => line.trim())
      .find((line) => line.length > 0) ?? "";

  const normalized = firstNonEmptyLine.replace(/\s+/g, " ").trim();

  if (normalized.length <= SESSION_TITLE_MAX_LENGTH) {
    return normalized;
  }

  return `${normalized.slice(0, SESSION_TITLE_MAX_LENGTH).trimEnd()}...`;
};

export const extractFirstUserText = (conversation: ConversationForTitle) => {
  if (conversation.type !== "user" || conversation.isSidechain === true) {
    return null;
  }

  const content = conversation.message?.content;
  if (typeof content === "string") {
    return content;
  }

  if (!Array.isArray(content)) {
    return null;
  }

  const firstContent = content.at(0);
  if (typeof firstContent === "string") {
    return firstContent;
  }

  if (
    firstContent &&
    firstContent.type === "text" &&
    typeof firstContent.text === "string"
  ) {
    return firstContent.text;
  }

  return null;
};

export const toDisplayMessage = (rawText: string): ParsedUserMessage | null => {
  if (ignoredExactTexts.has(rawText)) {
    return null;
  }

  const parsed = parseUserMessage(rawText);

  if (parsed.kind === "local-command") {
    return null;
  }

  if (parsed.kind === "command" && ignoredCommands.has(parsed.commandName)) {
    return null;
  }

  return parsed;
};

export const firstUserMessageToTitle = (firstCommand: ParsedUserMessage) => {
  switch (firstCommand.kind) {
    case "command":
      if (firstCommand.commandArgs === undefined) {
        return normalizeTitleText(firstCommand.commandName);
      }
      return normalizeTitleText(
        `${firstCommand.commandName} ${firstCommand.commandArgs}`,
      );
    case "local-command":
      return normalizeTitleText(firstCommand.stdout);
    case "text":
      return normalizeTitleText(firstCommand.content);
    default:
      firstCommand satisfies never;
      throw new Error("Invalid first command");
  }
};

export const getSessionTitleFromConversations = (
  conversations: ReadonlyArray<ConversationForTitle>,
): string | null => {
  for (const conversation of conversations) {
    const firstUserText = extractFirstUserText(conversation);
    if (firstUserText === null) {
      continue;
    }

    const parsed = toDisplayMessage(firstUserText);
    if (parsed === null) {
      continue;
    }

    return firstUserMessageToTitle(parsed);
  }

  return null;
};

export const countVisibleSessionMessagesFromConversations = (
  conversations: ReadonlyArray<ConversationForCount>,
): number => {
  return conversations.filter((conversation) => {
    if (conversation.type === "x-error") {
      return true;
    }

    if (conversation.type === "progress") {
      return false;
    }

    const isHiddenSidechain =
      conversation.type !== "summary" &&
      conversation.type !== "file-history-snapshot" &&
      conversation.type !== "queue-operation" &&
      conversation.isSidechain === true;

    if (isHiddenSidechain) {
      return false;
    }

    if (conversation.type !== "user") {
      return true;
    }

    const content = conversation.message?.content;
    if (!Array.isArray(content)) {
      return true;
    }

    return content.some(
      (item) => typeof item === "string" || item.type !== "tool_result",
    );
  }).length;
};

export const buildSessionDisplayMeta = (options: {
  sessionId: string;
  firstUserMessage: ParsedUserMessage | null;
  visibleMessageCount: number;
}): SessionDisplayMeta => {
  return {
    title:
      options.firstUserMessage !== null
        ? firstUserMessageToTitle(options.firstUserMessage)
        : options.sessionId,
    visibleMessageCount: options.visibleMessageCount,
  };
};

export const deriveSessionDisplayMetaFromConversations = (
  sessionId: string,
  conversations: ReadonlyArray<ConversationForTitle & ConversationForCount>,
): SessionDisplayMeta => {
  return {
    title: getSessionTitleFromConversations(conversations) ?? sessionId,
    visibleMessageCount:
      countVisibleSessionMessagesFromConversations(conversations),
  };
};

export const mergeSessionDisplayMetaWithVirtualConversations = (options: {
  sessionId: string;
  firstUserMessage: ParsedUserMessage | null;
  visibleMessageCount: number;
  virtualConversations: ReadonlyArray<
    ConversationForTitle & ConversationForCount
  >;
}): SessionDisplayMeta => {
  if (options.virtualConversations.length === 0) {
    return buildSessionDisplayMeta({
      sessionId: options.sessionId,
      firstUserMessage: options.firstUserMessage,
      visibleMessageCount: options.visibleMessageCount,
    });
  }

  return {
    title:
      options.firstUserMessage !== null
        ? firstUserMessageToTitle(options.firstUserMessage)
        : (getSessionTitleFromConversations(options.virtualConversations) ??
          options.sessionId),
    visibleMessageCount:
      options.visibleMessageCount +
      countVisibleSessionMessagesFromConversations(
        options.virtualConversations,
      ),
  };
};
