import { describe, expect, it } from "vitest";
import {
  countSessionMessagesFromConversations,
  firstUserMessageToTitle,
  getSessionTitleFromConversations,
} from "./firstCommandToTitle";

describe("firstCommandToTitle", () => {
  it("can convert parsed command to title", () => {
    const title = firstUserMessageToTitle({
      kind: "command",
      commandName: "/new",
      commandArgs: "feature-a",
    });

    expect(title).toBe("/new feature-a");
  });

  it("can extract title from first valid user conversation", () => {
    const title = getSessionTitleFromConversations([
      {
        type: "user",
        isSidechain: false,
        message: {
          content: "<command-name>/clear</command-name>",
        },
      },
      {
        type: "assistant",
        message: {
          content: "ok",
        },
      },
      {
        type: "user",
        isSidechain: false,
        message: {
          content: "实现登录页",
        },
      },
    ]);

    expect(title).toBe("实现登录页");
  });

  it("会压缩超长文本标题，避免会话列表和头部被整段提示词占满", () => {
    const title = firstUserMessageToTitle({
      kind: "text",
      content:
        "/opsx:new 请为以下内容创建新的 change，并进入 spec coding 流程。\n需求内容是一段非常长的说明，需要被压缩成适合标题展示的短文本。",
    });

    expect(
      title.startsWith("/opsx:new 请为以下内容创建新的 change，并进入 spec"),
    ).toBe(true);
    expect(title.endsWith("...")).toBe(true);
    expect(title.length).toBeLessThanOrEqual(43);
  });

  it("主会话标题会跳过清理类命令，回退到第一个有效消息", () => {
    const title = getSessionTitleFromConversations([
      {
        type: "user",
        isSidechain: false,
        message: {
          content: "<command-name>/clear</command-name>",
        },
      },
      {
        type: "user",
        isSidechain: false,
        message: {
          content:
            "/opsx:new 请为以下内容创建新的 change，并进入 spec coding 流程。\n这里是很长的后续描述。",
        },
      },
    ]);

    expect(title).toBe(
      "/opsx:new 请为以下内容创建新的 change，并进入 spec cod...",
    );
  });

  it("returns null when no valid user message exists", () => {
    const title = getSessionTitleFromConversations([
      {
        type: "assistant",
        message: {
          content: "processing",
        },
      },
      {
        type: "user",
        isSidechain: false,
        message: {
          content:
            "Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.",
        },
      },
    ]);

    expect(title).toBeNull();
  });

  it("会把会话区可见的 x-error 也计入消息数", () => {
    const count = countSessionMessagesFromConversations([
      { type: "user" },
      { type: "assistant" },
      { type: "x-error" },
      { type: "system" },
    ]);

    expect(count).toBe(4);
  });

  it("只统计会话区可见消息", () => {
    const count = countSessionMessagesFromConversations([
      { type: "progress" },
      {
        type: "user",
        message: {
          content: [{ type: "tool_result" }],
        },
      },
      { type: "assistant" },
      { type: "summary", isSidechain: false },
      { type: "assistant", isSidechain: true },
      { type: "x-error" },
    ]);

    expect(count).toBe(3);
  });
});
